packageExtensions:
    '@jest/core@*':
        dependencies:
            ts-node: ^10.9.2
            typescript: ^5.0.0
    '@open-rpc/generator@*':
        dependencies:
            '@inquirer/prompts': ^3.0.0
            '@open-rpc/schema-utils-js': ^2.0.2
