npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
    '@canton-network/core-wallet-dapp-rpc-client@*':
        dependencies:
            '@typescript-eslint/parser': '*'
            eslint: '*'
    '@canton-network/core-wallet-user-rpc-client@*':
        dependencies:
            '@typescript-eslint/parser': '*'
            eslint: '*'
    '@daml.js/daml-stdlib-DA-Time-Types-1.0.0@*':
        dependencies:
            '@daml/ledger': 3.3.0-snapshot.20250528.13806.0.v3cd439fb
            '@daml/types': 3.3.0-snapshot.20250528.13806.0.v3cd439fb
    '@daml.js/ghc-stdlib-DA-Internal-Template-1.0.0@*':
        dependencies:
            '@daml/ledger': 3.3.0-snapshot.20250528.13806.0.v3cd439fb
            '@daml/types': 3.3.0-snapshot.20250528.13806.0.v3cd439fb
    '@daml.js/token-standard-models-1.0.0@*':
        dependencies:
            '@daml/ledger': 3.3.0-snapshot.20250528.13806.0.v3cd439fb
            '@daml/types': 3.3.0-snapshot.20250528.13806.0.v3cd439fb
    '@daml/ledger@*':
        dependencies:
            lodash: ^4.17.21
    '@jest/core@*':
        dependencies:
            ts-node: ^10.9.2
            typescript: ^5.0.0
    '@json-schema-tools/reference-resolver@*':
        dependencies:
            '@json-schema-tools/meta-schema': '*'
    '@open-rpc/generator@*':
        dependencies:
            '@inquirer/prompts': ^3.0.0
            '@open-rpc/schema-utils-js': ^2.0.2
    undici-types@*:
        dependencies:
            '@types/node': '*'
    vite-express@*:
        dependencies:
            vite: '*'
