packageExtensions:
    '@open-rpc/generator@*':
        dependencies:
            '@open-rpc/schema-utils-js': '^2.0.2'
            '@inquirer/prompts': '^3.0.0'
    '@open-rpc/server-js@*':
        dependencies:
            '@open-rpc/meta-schema': '*'
            '@types/connect': '*'
            '@types/cors': '*'
    '@json-schema-tools/reference-resolver@*':
        dependencies:
            '@json-schema-tools/meta-schema': '*'
