packageExtensions:
    '@open-rpc/generator@*':
        dependencies:
            '@inquirer/prompts': ^3.0.0
            '@open-rpc/schema-utils-js': ^2.0.2
    '@jest/core@*':
        dependencies:
            'ts-node': ^10.9.2
            'typescript': ^5.0.0
    '@json-schema-tools/reference-resolver@*':
        dependencies:
            '@json-schema-tools/meta-schema': '*'
    '@open-rpc/client-js@*':
        dependencies:
            '@types/node': '*'
            '@types/isomorphic-fetch': '*'
            '@types/ws': '*'
    'undici-types@*':
        dependencies:
            '@types/node': '*'
    'core-wallet-dapp-rpc-client@*':
        dependencies:
            '@typescript-eslint/parser': '*'
            'eslint': '*'
