#temp, remove it once issues with imports from within daml codegen are resolved
pnpMode: 'loose'

packageExtensions:
    '@jest/core@*':
        dependencies:
            ts-node: ^10.9.2
            typescript: ^5.0.0
    '@json-schema-tools/reference-resolver@*':
        dependencies:
            '@json-schema-tools/meta-schema': '*'
    '@open-rpc/generator@*':
        dependencies:
            '@inquirer/prompts': ^3.0.0
            '@open-rpc/schema-utils-js': ^2.0.2
    core-wallet-dapp-rpc-client@*:
        dependencies:
            '@typescript-eslint/parser': '*'
            eslint: '*'
    core-wallet-user-rpc-client@*:
        dependencies:
            '@typescript-eslint/parser': '*'
            eslint: '*'
    undici-types@*:
        dependencies:
            '@types/node': '*'
    vite-express@*:
        dependencies:
            vite: '*'
    '@daml.js/exercise-app-0.1.0@*':
        peerDependencies:
            '@daml/ledger': '3.3.0-snapshot.20250502.13767.0.v2fc6c7e2'
            '@daml/types': '3.3.0-snapshot.20250502.13767.0.v2fc6c7e2'
