// Copyright (c) 2025-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { dereference } from '@scalar/openapi-parser'
import { getRepoRoot } from './lib/utils.js'
import * as fs from 'node:fs/promises'
import { bundle } from '@scalar/json-magic/bundle'
import { fetchUrls } from '@scalar/json-magic/bundle/plugins/browser'
import { readFiles } from '@scalar/json-magic/bundle/plugins/node'
import path from 'node:path'
import { LedgerApiTypeGenerator } from './lib/ledgerapi-type-generator.js'

const REPO_ROOT = getRepoRoot()
const LAPI_VERSION = '3.4.11'
const OUTPUT_PATH = `${REPO_ROOT}/core/splice-provider/src/ledger-provider/${LAPI_VERSION}/ledger-api-types.ts`

async function loadOpenApiSpec(version: string) {
    const path = `${REPO_ROOT}/api-specs/ledger-api/${version}/openapi.yaml`
    console.log(`Dereferencing OpenAPI spec at: ${path}`)

    const accessible = await fs.access(path, fs.constants.F_OK).then(
        () => true,
        () => false
    )

    if (accessible) {
        console.log('File exists, proceeding with dereferencing...')
    } else {
        console.error(`File not found at path: ${path}`)
        process.exit(1)
    }

    // Load a file and all referenced files
    const data = await bundle(path, {
        plugins: [
            readFiles(),
            fetchUrls({
                limit: 5,
            }),
        ],
        treeShake: false,
    })

    return dereference(data)
}

async function main() {
    const { specification } = await loadOpenApiSpec(LAPI_VERSION)
    if (!specification) {
        throw new Error('Failed to load OpenAPI specification')
    }

    const generator = new LedgerApiTypeGenerator(specification)

    let fileContent = `// This file is auto-generated by scripts/src/generate-openapi-types.ts\n\n`

    fileContent += generator.generateComponents()
    fileContent += generator.generateLedgerTypes()

    await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true })
    await fs.writeFile(OUTPUT_PATH, fileContent)
}

main().catch((err) => {
    console.error('Error generating types:', err)
    process.exit(1)
})
