name: Check resource usage
description: 'List current resource usage of the CI runner VM'
runs:
    using: composite
    steps:
        - name: Check memory usage
          if: always()
          shell: bash
          run: free -h

        - name: Check CPU usage
          if: always()
          shell: bash
          run: top -n10 -stats pid,command,cpu,threads,mem,time
