name: Setup Yarn
description: 'Setup Yarn for the project'
runs:
    using: composite
    steps:
        - name: Enable Corepack
          shell: bash
          run: corepack enable

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: 'v22.16.0'
              cache: 'yarn'

        - name: Install dependencies
          shell: bash
          run: yarn install --immutable

        - uses: actions/cache@v4
          with:
              path: |
                  .nx/cache
                  .nx/workspace-data
              key: nx-${{ github.ref }}
              restore-keys: |
                  nx-
