name: Setup Yarn
description: 'Setup Yarn for the project'
runs:
    using: composite
    steps:
        - name: Enable Corepack
          shell: bash
          run: corepack enable

        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
              node-version: 'v24.9.0'
              cache: 'yarn'

        - name: Install dependencies
          shell: bash
          run: yarn install --immutable

        - name: Restore Nx cache
          uses: actions/cache/restore@v5
          with:
              path: |
                  .nx/cache
                  .nx/workspace-data
              key: nx-${{ github.run_id }}
