// Code generated by @open-rpc/generator DO NOT EDIT.
import _ from 'lodash'

import { RequestPayload, RpcTransport } from '@hyperledger-labs/core-types'

/**
 *
 * Name of network
 *
 */
export type Name = string
/**
 *
 * Description of network
 *
 */
export type Description = string
/**
 *
 * Synchronizer ID
 *
 */
export type SynchronizerId = string
/**
 *
 * Network Id
 *
 */
export type ChainId = string
export type Type = string
export type TokenUrl = string
export type GrantType = string
export type Scope = string
export type ClientId = string
export type Issuer = string
export type ConfigUrl = string
export type Audience = string
/**
 *
 * Represents the type of auth (implicit or password) for a specified network
 *
 */
export interface Auth {
    authType?: Type
    tokenUrl?: TokenUrl
    grantType?: GrantType
    scope?: Scope
    clientId?: ClientId
    issuer: Issuer
    configUrl: ConfigUrl
    audience?: Audience
    [k: string]: any
}
/**
 *
 * Ledger api url
 *
 */
export type LedgerApi = string
/**
 *
 * Structure representing the Networks
 *
 */
export interface Network {
    name: Name
    description: Description
    synchronizerId: SynchronizerId
    chainId: ChainId
    auth: Auth
    ledgerApi: LedgerApi
}
/**
 *
 * Ledger api url
 *
 */
export type NetworkName = string
/**
 *
 * Set as primary wallet for dApp usage.
 *
 */
export type Primary = boolean
/**
 *
 * The party hint and name of the wallet.
 *
 */
export type PartyHint = string
/**
 *
 * The signing provider ID the wallet corresponds to.
 *
 */
export type SigningProviderId = string
export type PartyId = string
/**
 *
 * Filter wallets by network IDs.
 *
 */
export type ChainIds = ChainId[]
/**
 *
 * Filter wallets by signing provider IDs.
 *
 */
export type SigningProviderIds = SigningProviderId[]
/**
 *
 * Filter for the wallets to be returned.
 *
 */
export interface WalletFilter {
    chainIds?: ChainIds
    signingProviderIds?: SigningProviderIds
    [k: string]: any
}
export type PreparedTransaction = string
export type PreparedTransactionHash = string
/**
 *
 * The command ID of the transaction to be executed.
 *
 */
export type CommandId = string
export type Signature = string
export type SignedBy = string
/**
 *
 * The party hint and name of the wallet.
 *
 */
export type Hint = string
/**
 *
 * The public key of the party.
 *
 */
export type PublicKey = string
/**
 *
 * The namespace of the party.
 *
 */
export type Namespace = string
/**
 *
 * Structure representing a wallet
 *
 */
export interface Wallet {
    primary: Primary
    partyId: PartyId
    hint: Hint
    publicKey: PublicKey
    namespace: Namespace
    chainId: ChainId
    signingProviderId: SigningProviderId
    [k: string]: any
}
export type Networks = Network[]
/**
 *
 * The access token for the session.
 *
 */
export type AccessToken = string
export type Status = 'connected' | 'disconnected'
/**
 *
 * Structure representing the connected network session
 *
 */
export interface Session {
    network: Network
    accessToken: AccessToken
    status: Status
}
export type Sessions = Session[]
export interface AddNetworkParams {
    network: Network
    [k: string]: any
}
export interface RemoveNetworkParams {
    networkName: NetworkName
    [k: string]: any
}
export interface CreateWalletParams {
    primary?: Primary
    partyHint: PartyHint
    chainId: ChainId
    signingProviderId: SigningProviderId
    [k: string]: any
}
export interface SetPrimaryWalletParams {
    partyId: PartyId
    [k: string]: any
}
export interface RemoveWalletParams {
    partyId: PartyId
    [k: string]: any
}
export interface ListWalletsParams {
    filter?: WalletFilter
    [k: string]: any
}
export interface SignParams {
    preparedTransaction: PreparedTransaction
    preparedTransactionHash: PreparedTransactionHash
    commandId: CommandId
    partyId: PartyId
    [k: string]: any
}
export interface ExecuteParams {
    signature: Signature
    partyId: PartyId
    commandId: CommandId
    signedBy: SignedBy
    [k: string]: any
}
export interface AddSessionParams {
    chainId: ChainId
    [k: string]: any
}
/**
 *
 * Represents a null value, used in responses where no data is returned.
 *
 */
export type Null = null
export interface CreateWalletResult {
    wallet: Wallet
    [k: string]: any
}
export interface RemovePartyResult {
    [key: string]: any
}
/**
 *
 * An array of wallets that match the filter criteria.
 *
 */
export type ListWalletsResult = Wallet[]
export interface SignResult {
    signature: Signature
    partyId: PartyId
    signedBy: SignedBy
    [k: string]: any
}
export interface ExecuteResult {
    [key: string]: any
}
export interface ListNetworksResult {
    networks: Networks
    [k: string]: any
}
/**
 *
 * Structure representing the connected network session
 *
 */
export interface AddSessionResult {
    network: Network
    accessToken: AccessToken
    status: Status
}
export interface ListSessionsResult {
    sessions: Sessions
    [k: string]: any
}
/**
 *
 * Generated! Represents an alias to any of the provided schemas
 *
 */

export type AddNetwork = (params: AddNetworkParams) => Promise<Null>
export type RemoveNetwork = (params: RemoveNetworkParams) => Promise<Null>
export type CreateWallet = (
    params: CreateWalletParams
) => Promise<CreateWalletResult>
export type SetPrimaryWallet = (params: SetPrimaryWalletParams) => Promise<Null>
export type RemoveWallet = (
    params: RemoveWalletParams
) => Promise<RemovePartyResult>
export type ListWallets = (
    params: ListWalletsParams
) => Promise<ListWalletsResult>
export type Sign = (params: SignParams) => Promise<SignResult>
export type Execute = (params: ExecuteParams) => Promise<ExecuteResult>
export type ListNetworks = () => Promise<ListNetworksResult>
export type AddSession = (params: AddSessionParams) => Promise<AddSessionResult>
export type ListSessions = () => Promise<ListSessionsResult>

export class SpliceWalletJSONRPCUserAPI {
    public transport: RpcTransport

    constructor(transport: RpcTransport) {
        this.transport = transport
    }

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'addNetwork',
        ...params: Parameters<AddNetwork>
    ): ReturnType<AddNetwork>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'removeNetwork',
        ...params: Parameters<RemoveNetwork>
    ): ReturnType<RemoveNetwork>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'createWallet',
        ...params: Parameters<CreateWallet>
    ): ReturnType<CreateWallet>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'setPrimaryWallet',
        ...params: Parameters<SetPrimaryWallet>
    ): ReturnType<SetPrimaryWallet>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'removeWallet',
        ...params: Parameters<RemoveWallet>
    ): ReturnType<RemoveWallet>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'listWallets',
        ...params: Parameters<ListWallets>
    ): ReturnType<ListWallets>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'sign',
        ...params: Parameters<Sign>
    ): ReturnType<Sign>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'execute',
        ...params: Parameters<Execute>
    ): ReturnType<Execute>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'listNetworks',
        ...params: Parameters<ListNetworks>
    ): ReturnType<ListNetworks>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'addSession',
        ...params: Parameters<AddSession>
    ): ReturnType<AddSession>

    /**
     *
     */
    // tslint:disable-next-line:max-line-length
    public async request(
        method: 'listSessions',
        ...params: Parameters<ListSessions>
    ): ReturnType<ListSessions>

    public async request(
        method: string,
        params?: RequestPayload['params']
    ): Promise<unknown> {
        const response = await this.transport.submit({ method, params })

        if ('error' in response) {
            throw new Error(
                'RPC error: ' +
                    response.error.code +
                    ' - ' +
                    response.error.message
            )
        } else {
            return response.result
        }
    }
}
export default SpliceWalletJSONRPCUserAPI
