name: CI on PRs
run-name: ${{ github.actor }} is perfoming a Pull Request

on:
    pull_request:
        types: [opened, reopened, synchronize, edited]
    pull_request_target:
        types: [opened, reopened, synchronize, edited]
permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.event_name }}
    cancel-in-progress: true

jobs:
    ci-internal:
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false && !contains(github.event.pull_request.title, 'chore(release):')
        uses: ./.github/workflows/build-primary.yml
        with:
            checkout_ref: ${{ github.event.pull_request.head.sha }}
            pr_number: ${{ github.event.pull_request.number }}
            pr_title: ${{ github.event.pull_request.title }}
            pr_head_sha: ${{ github.event.pull_request.head.sha }}
            pr_base_ref: ${{ github.base_ref }}

    ci-fork:
        if: github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork == true && !contains(github.event.pull_request.title, 'chore(release):')
        uses: ./.github/workflows/build-primary.yml
        with:
            checkout_ref: ${{ github.event.pull_request.head.sha }}
            pr_number: ${{ github.event.pull_request.number }}
            pr_title: ${{ github.event.pull_request.title }}
            pr_head_sha: ${{ github.event.pull_request.head.sha }}
            pr_base_ref: ${{ github.base_ref }}
