name: Release packages
run-name: ${{ github.actor }} is cutting a release
on:
    push:
        branches:
            - latest
            - release/**
permissions:
    contents: read
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'v22.16.0'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Release
              run: yarn nx release --dry-run --skip-publish # Skip publish until we get an NPM token setup

            - run: git push --tags
