name: Version and release
run-name: ${{ github.actor }} is cutting a release
on:
    pull_request:
        types: [opened, reopened, synchronize, edited]
        branches:
            - latest
permissions:
    contents: write
    pull-requests: write
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Enable Corepack
              run: corepack enable

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'v22.16.0'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Set git metadata
              run: |
                  git config --global user.name github-actions
                  git config --global user.email github-actions@github.com

            - name: Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: yarn nx release --skip-publish

            - name: Open Version Bump PR
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  BRANCH_NAME=ci/${{ github.run_id }}
                  RELEASE_COMMIT_HASH=$(git log --pretty=oneline | grep "chore(release)" | cut -d " " -f 1)

                  if [[ -z $RELEASE_COMMIT_HASH ]]; then
                      echo "No release commit found"
                      exit 1
                  fi

                  git checkout main
                  git branch $BRANCH_NAME

                  git checkout $BRANCH_NAME
                  git cherry-pick $RELEASE_COMMIT_HASH

                  git push origin $BRANCH_NAME

                  gh pr create -f -a ${{ github.actor }} -B main
