name: Version and release
run-name: ${{ github.actor }} is cutting a release
on:
    pull_request:
        types: [opened, reopened, synchronize, edited]
        branches:
            - latest
permissions:
    contents: write
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Enable Corepack
              run: corepack enable

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'v22.16.0'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Set git metadata
              run: |
                  git config --global user.name github-actions
                  git config --global user.email github-actions@github.com

            - name: Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: yarn nx release --skip-publish
