name: Release packages
run-name: ${{ github.actor }} is cutting a release
on:
    push:
        branches:
            - latest
            - alex/tweak-release-config
permissions:
    contents: write
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Enable Corepack
              run: corepack enable

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'v22.16.0'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - run: git config --global user.name github-actions
            - run: git config --global user.email github-actions@github.com

            - name: Release
              run: yarn nx release --skip-publish # Skip publish until we get an NPM token setup
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - run: git log
            # - run: git push --tags
